### ISSUE TITLE
How to get app to work

### ISSUE THREAD

**Issue by chrisloughnane** [hakdogan/ApacheShiro#2]
Hi hakdogan,

 While trying to teach myself Shiro I found your repo but I've been unable to get it to work. The app starts fine and I added my credentials:
u: chris
p: chris (SHA-2565 5d7f15f2fce8ddb2dbef5c38be896c238ba7e0a432e396759030a853fa6b1151)

and added my role as _admin_ but I still can't log in. 

Could you tell me if there are any other steps required?

**Comment by chrisloughnane** [comment]
I'm so sorry, I just realised I hadn't set up the credentials for the db. Everything is working fine now 👍

**Comment by hakdogan** [comment]
Hi @chrisloughnane 

I'm sorry to notice late. Fortunately, you have identified and solved the problem 👍
