### ISSUE TITLE
Could you please tell me how the app knows to use loginUser() to confirm logins

### ISSUE THREAD

**Issue by chrisloughnane** [hakdogan/ApacheShiro#3]
I've spent near a week trying to add Shiro to my app that uses jsp pages but I cannot get it to authenticate a user from a db entry.

**Comment by hakdogan** [comment]
Hi @chrisloughnane 

The ShiroBean is a faces bean it has String username, password, and boolean rememberMe attributes. These attributes binding via login.xhtml.

```
<h:inputText value="#{shiroBean.username}"
      required="true" requiredMessage="The username value is required." size="30"/>

   <p>Password</p>
   <h:inputSecret value="#{shiroBean.password}"
       required="true" requiredMessage="The password value is required." size="30"/>
   
   <h:outputLabel/>
   <h:panelGroup>
      <h:selectBooleanCheckbox value="#{shiroBean.rememberMe}" />
```

Then, these values handled in the loginUser method.

```
Subject currentUser   = SecurityUtils.getSubject();
UsernamePasswordToken token = new UsernamePasswordToken(username, new Sha256Hash(password).toHex());

token.setRememberMe(rememberMe);
currentUser.login(token);
```

So, you must need login values in this method. Are you provided these values with jsp?

**Comment by chrisloughnane** [comment]
Hi hakdogan,

 Thanks for taking the time to reply. I had the JSP pages setup correctly and it wasn't until yesterday we found the problem, it wouldn't work on GlassFish but works fine on Jetty. 

Thanks for your great example 😀
